services:
  chea-kg-timeseries:
    build: .
    image: avdusen25/chea-kg-timeseries:0.1.4
    # image: maayanlab/chea-kg-timeseries:0.2.12
    restart: unless-stopped
    pull_policy: missing
    platform: linux/amd64
    environment:
    - APPYTER_PUBLIC_URL=https://chea-kg-timeseries.k8s.dev.maayanlab.cloud
    - APPYTER_PROXY=true
    - APPYTER_FUSE=false
    ports:
    - 5050:5000
    x-kubernetes:
      annotations:
        maayanlab.cloud/ingress: https://chea-kg-timeseries.k8s.dev.maayanlab.cloud
x-kubernetes:
  name: chea-kg-timeseries
  namespace: avdusen25
