services:
  chea-kg-timeseries:
    build: .
    # image: abird128/chea-kg-timeseries:0.4.0
    image: abird128/chea-kg-timeseries:0.4.0
    restart: unless-stopped
    pull_policy: missing
    platform: linux/amd64
    environment:
    - APPYTER_PUBLIC_URL
    - APPYTER_PROXY=true
    - APPYTER_DATA_DIR
    - APPYTER_EXECUTOR=kube::abird128/chea-kg-timeseries:0.4.0#?namespace=${KUBE_NAMESPACE}&resources.requests.memory=8Gi
    ports:
    - 5050:5000
    x-kubernetes:
      annotations:
        maayanlab.cloud/ingress: ${APPYTER_PUBLIC_URL}
      serviceAccountName: chea-kg-timeseries-sa

x-kubernetes:
  name: chea-kg-timeseries
  namespace: ${KUBE_NAMESPACE}
  apply: |
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: chea-kg-timeseries-sa
      namespace: ${KUBE_NAMESPACE}
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: chea-kg-timeseries-role
      namespace: ${KUBE_NAMESPACE}
    rules:
    - apiGroups:
      - ""
      resources:
      - pods
      verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    - apiGroups:
      - batch
      - extensions
      resources:
      - jobs
      verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: chea-kg-timeseries-role-binding
      namespace: ${KUBE_NAMESPACE}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: chea-kg-timeseries-role
    subjects:
    - kind: ServiceAccount
      name: chea-kg-timeseries-sa
      namespace: ${KUBE_NAMESPACE}
